type ImportStatus = {
  tone: "info" | "success" | "error";
  message: string;
};

type ReportSource = {
  kind: "sample" | "pasted" | "file";
  label: string;
};

type ReportImportPanelProps = {
  pastedJson: string;
  source: ReportSource;
  status: ImportStatus;
  onPastedJsonChange: (value: string) => void;
  onLoadPastedJson: () => void;
  onLoadFile: (file: File) => void;
  onUseSample: () => void;
};

export function ReportImportPanel({
  pastedJson,
  source,
  status,
  onPastedJsonChange,
  onLoadPastedJson,
  onLoadFile,
  onUseSample,
}: ReportImportPanelProps) {
  return (
    <section id="import" className="import-panel" aria-labelledby="import-heading">
      <div className="section-heading compact">
        <p>Browser-only import</p>
        <h2 id="import-heading">Load a local report without uploading anything.</h2>
      </div>
      <div className="import-layout">
        <div className="import-copy">
          <p>
            Choose or paste the report.json generated by the CLI. Parsing happens entirely in this browser session; there is no
            backend, auth, analytics, or secret storage.
          </p>
          <div className="active-report-pill">
            <span>Active report</span>
            <strong>{source.label}</strong>
          </div>
          <label className="file-picker">
            <span>Import report.json file</span>
            <input
              type="file"
              accept="application/json,.json"
              onChange={(event) => {
                const file = event.currentTarget.files?.[0];
                if (file) {
                  onLoadFile(file);
                  event.currentTarget.value = "";
                }
              }}
            />
          </label>
        </div>
        <div className="paste-card">
          <label htmlFor="report-json">Paste report JSON</label>
          <textarea
            id="report-json"
            value={pastedJson}
            placeholder='{"schemaVersion":"1.0.0","target":{"url":"https://example.com"}...}'
            spellCheck={false}
            onChange={(event) => onPastedJsonChange(event.currentTarget.value)}
          />
          <div className="import-actions">
            <button type="button" className="primary-action" onClick={onLoadPastedJson}>
              Load pasted JSON
            </button>
            <button type="button" className="secondary-action" onClick={onUseSample} disabled={source.kind === "sample"}>
              Use sample data
            </button>
          </div>
          <p className={`import-status ${status.tone}`} role="status">
            {status.message}
          </p>
        </div>
      </div>
    </section>
  );
}

export type { ImportStatus, ReportSource };
